name: Build Documentation

on:
  push:
    branches:
      - main

jobs:
  build_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Install Tools
        run: |
          sudo apt-get install dbtoepub docbook-xsl fop libsaxon-java libxml2-utils libxslthl-java xsltproc && \
          gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB && \
          curl -sSL https://get.rvm.io | bash -s stable && \
          source /home/runner/.rvm/scripts/rvm && \
          rvm use system

      - name: Get phing
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: phing:3.0.0-RC3

      - name: Build documentation
        run: phing -debug

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
